#!/bin/sh

# This script can be used to rewrite the schema in svn working copy URLs,
# changing URLs that use 'http' as an access method to use 'svn+ssh' instead.
# (The http: access method allows read-only access; 'svn+ssh' allows people
# with appropriate permission to commit changes to the repository.)

HTTP_URL=http://svn.clozure.com
SSH_URL=svn+ssh://svn.clozure.com/usr/local
CCLDIR=`dirname $0`/..

# This assumes that all directories under CCL are under svn control
# That's a reasonable assumption after a fresh checkout; if it's
# violated, svn will warn and we'll move on.

for d in `ls $CCLDIR`
do
 if [ -d $CCLDIR/$d ]; then
   (cd $CCLDIR/$d ; 
    echo Relocating `pwd` ; 
    svn switch --relocate $HTTP_URL $SSH_URL)
 fi
done
